version: "3"

services:
  back:
    build:
      context: ./
      dockerfile: .dockerfiles/back-dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    restart: always

  front:
    build:
      context: ./
      dockerfile: .dockerfiles/front-dev
    ports:
      - "3000:3000"
    volumes:
      - ./front:/opt/app
      - /opt/app/node_modules
    environment:
      - NODE_ENV=development
    restart: always
    stdin_open: true
    tty: true